### ISSUE TITLE
Roundup Week of 13 December

### ISSUE THREAD

**Issue by murillol** [WordPress/Marcomms-Meetups#31]
This week we have a lot going on! Don't miss these online #WordPress meetups:

WordPress Cambridge (UK) on 13 December 2021, 7.00pm UTC/GMT. Join this session to share your favourite themes and discover others. All themes and questions welcome.

Sign-Up: https://www.meetup.com/wordpress-cambridge/events/282307137/

--

WordPress Hartford (USA) on 13 December 2021, 11.00pm UTC (6.00pm EST). Learn how to implement some basic SEO best-practices on your WordPress website, using free tools.

 RSVP: https://www.meetup.com/WordPressHartford/events/282470987/

--

WordPress Greater Milwaukee (USA) on 15 December 2021, 12.00am UTC (14 December 6.00pm CST). Learn how to create a custom button in your secondary menu bar, then get all your questions answered in the Q&A!

Book: https://www.meetup.com/Milwaukee-WordPress-MeetUp/events/hntnvryccqbsb/

--

WordPress Naperville (USA) on 15 December 2021, 12.30am UTC (14 December 6.30pm CST). Learn how to build three different kinds of custom block functionality that can make content editing easier for you or your clients: Reusable blocks, block patterns, and block templates.

Sign-Up: https://www.meetup.com/WordPress-Naperville/events/vzstwryccqbcc/

--

WordPress Portsmouth (UK) on 15 December 2021, 7.00pm UTC/GMT. Join for an introduction to WordPress plugin development!

RSVP: https://www.meetup.com/Portsmouth-WordPress-Meetup/events/282355917/

--

WordPress Oklahoma City (USA) on 16 December 2021, 4.00pm UTC (10.00am CST). Are you using Gutenberg yet? Have you made the switch for yourself and your clients? We’ll explore the up-to-date best places for Gutenberg training on-line and how you can clone your site so you can safely play and test your site before the big switch.

RSVP: https://www.meetup.com/OKC-WordPress-Users-Group/events/282196504/

--

Reminder: there will be many State of the Word Watch Parties on 14 and 15 December 2021, so be sure to check if your local Meetup is hosting one: https://wordpress.org/news/2021/11/watch-state-of-the-word-at-a-watch-party-with-your-wordpress-friends/

#OnlineWPMeetup

**[Published Post](https://www.linkedin.com/posts/make-wordpress-marketing-team_meetup-we-are-what-we-do-activity-6876174721600278529-txNO)**

**Comment by murillol** [comment]
ready @yvettesonneveld!

**Comment by nalininsbs** [comment]
Transferring to the WordPress Marketing - Team board

Props to: @murillol @yvettesonneveld @abhansnuk
